# Generated by Django 3.1.7 on 2023-12-16 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0003_photo_shooting'),
    ]

    operations = [
        migrations.AddField(
            model_name='shooting',
            name='cover',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
