# Generated by Django 3.1.7 on 2024-01-19 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0004_shooting_cover'),
    ]

    operations = [
        migrations.CreateModel(
            name='TitlePane',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=100)),
                ('redirectLink', models.CharField(max_length=100)),
                ('image', models.ImageField(null=True, upload_to='images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
