# Generated by Django 3.1.7 on 2024-01-19 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0005_titlepane'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titlepane',
            name='redirectLink',
            field=models.CharField(default='/', max_length=100),
        ),
    ]
